Initial version of letsencrypt.py for review
mysociety/ssl-scripts pull request #1
Opened 2016-10-04 11:10 UTC by hazelesque

### Summary

This is the first draft script for automating letsencrypt SSL issuance, using data from vhosts.pl.

There are undoubtedly issues with this script, but it does at least work. It has been tested against both the staging and production CAs.

Could you review this and see what you think?

2016-10-04 13:38 UTC, dracos requested changes
Looks good, some suggested changes but nothing to the substance. I guess one extra thing it could do would be check the current expiry date of a matching cert in /data/servers/certificates and not do anything if there's plenty of time left.

2016-10-04 13:38 UTC, dracos commented on letsencrypt.py
> +        subprocess.check_call(cmd_prefix + ['simp_le', '--email', 'infrastructure@mysociety.org', '--default_root', '/data/letsencrypt/webroot/', '-d', cn] + all_but_cn_args + ['-f', 'key.pem', '-f',
Could this (and other long lines) be wrapped to a max of 119 characters, which is what we use on other python projects.

2016-10-04 13:38 UTC, dracos commented on letsencrypt.py
> +        data = self.known_vhosts[vhost_name]
Some error handling here in case the vhost name isn't found?

2016-10-04 13:38 UTC, dracos commented on letsencrypt.py
> +            pass # Not yet implemented
I'd remove this code for now then :)

2016-10-04 13:38 UTC, dracos commented on letsencrypt.py
> +        aliases = data.get('aliases', list())
We generally use `[]` for the empty list.

2016-10-04 13:38 UTC, dracos commented on letsencrypt.py
> +    def __init__(self):
I don't think you need to specify an empty `__init__`.

2016-10-04 13:38 UTC, dracos commented on letsencrypt.py
> +        self.known_sites, self.known_vhosts = self._parse_vhosts_pl(args.vhosts_pl_path)
Sites isn't used in this script at the moment; I can't think of what it would be for in anything obvious, so perhaps this can be removed.

2016-10-04 13:38 UTC, dracos commented on letsencrypt.py
> +        all_but_cn = set(dns_names)
As dns_names is already a set, pehaps dns_names.copy() would be clearer.

2016-10-04 13:38 UTC, dracos commented on letsencrypt.py
> +        for v in all_but_cn:
As you go on to use -d CN first in the actual call, and this is a list you're constructing, would it be easier to start your list with the CN and then append all the others?

2016-10-04 13:38 UTC, dracos commented on letsencrypt.py
> +        subprocess.check_call(cmd_prefix + ['simp_le', '--email', 'infrastructure@mysociety.org', '--default_root', '/data/letsencrypt/webroot/', '-d', cn] + all_but_cn_args + ['-f', 'key.pem', '-f',
As simp_le is a python script, could this be done with something like "from simp_le import main as simp_le" and then called as a function, or do we prefer calling out to it.

2016-10-04 13:38 UTC, dracos commented on letsencrypt.py
> +        which_vhosts_group.add_argument('--vhost', action='append', dest='vhosts', default=list(), help="Specify a particular vhost")
Should vhosts perhaps be named arguments rather than having to specify `--vhost`.

2016-10-06 10:03 UTC, mhl commented on letsencrypt.py
> +        subprocess.check_call(cmd_prefix + ['simp_le', '--email', 'infrastructure@mysociety.org', '--default_root', '/data/letsencrypt/webroot/', '-d', cn] + all_but_cn_args + ['-f', 'key.pem', '-f',
I'd like to add a small vote for using `check_call`: we might well switch to an alternative Let's Encrypt client at another stage, and if it's invoked as a separate process (rather than being a Python function call) it's clear that anything else can be swapped in easily.

2016-10-06 10:05 UTC, dracos commented on letsencrypt.py
> +        subprocess.check_call(cmd_prefix + ['simp_le', '--email', 'infrastructure@mysociety.org', '--default_root', '/data/letsencrypt/webroot/', '-d', cn] + all_but_cn_args + ['-f', 'key.pem', '-f',
Yep, fair enough :)

2016-10-24 12:36 UTC, dracos approved these changes

2016-10-24 12:36 UTC, merged